name: Build Android AAB (Play Store)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository ni yuklab olish
        uses: actions/checkout@v4

      - name: Python o'rnatish
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Java o'rnatish (Android build uchun kerak)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Flet va flet-cli o'rnatish
        run: |
          pip install flet==0.28.3
          pip install flet-cli==0.28.3

      - name: AAB build qilish (Play Store uchun)
        run: |
          flet build aab --verbose

      - name: AAB faylni saqlash (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: doit-aab
          path: build/aab/*.aab
          retention-days: 30
